name: "Mailer-Deployment"
on:
  push:
    branches:
       - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Greet user
        run: echo "Welcome Mr Dapo"
      - name: Build image
        run: docker build -t dapper92/practice-image:1 .