name: "Mailer-Deployment"
on:
  push:
    branches:
       - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: Greet user
        run: echo "Welcome Mr Dapo"